const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');
module.exports=async(pet,getSettings,openSettings,action,state,timer)=>{
 if(!pet.isVisible())await new Promise(resolve=>pet.once('show',resolve));
 const out=path.join(__dirname,'../qa');fs.mkdirSync(out,{recursive:true});
 const errors=[];pet.webContents.on('console-message',(_,details)=>{if(details.level==='error')errors.push(details.message);});
 await pet.webContents.executeJavaScript(`Promise.all([document.fonts.ready,image.decode()])`);
 assert.equal(pet.isAlwaysOnTop(),true);assert.equal(pet.isVisible(),true);
 assert.equal(await pet.webContents.executeJavaScript('image.naturalWidth'),500);
 assert.equal(await pet.webContents.executeJavaScript('hitTest(1,1)'),false);
 assert.equal(await pet.webContents.executeJavaScript(`(()=>{const b=$('timerBadge').getBoundingClientRect();return hitTest(b.x+5,b.y+5);})()`),true);
 const before=pet.getBounds();pet.setPosition(before.x-50,before.y-30);assert.equal(pet.getBounds().x,before.x-50);pet.setBounds(before);
 openSettings();const w=getSettings();if(w.webContents.isLoading())await new Promise(r=>w.webContents.once('did-finish-load',r));
 await w.webContents.executeJavaScript(`document.fonts.ready`);
 await w.webContents.executeJavaScript(`window.workFeiBi.saveSettings({soundEnabled:false,volume:40})`);
 assert.equal(state().settings.soundEnabled,false);
 await w.webContents.executeJavaScript(`window.workFeiBi.saveSettings({outfit:0})`);
 assert.match(await pet.webContents.executeJavaScript(`image.src`),/phoebe_0/);
 await w.webContents.executeJavaScript(`window.workFeiBi.saveSettings({outfit:1})`);
 await pet.webContents.executeJavaScript(`image.decode()`);
 action('toggle');assert.equal(state().timer.running,true);action('toggle');assert.equal(state().timer.running,false);
 timer.toggle();timer.deadline=Date.now()-61000;
 await pet.webContents.executeJavaScript(`new Promise(resolve=>{if(state.timer.angry)resolve();else window.workFeiBi.onState(s=>{if(s.timer.angry)resolve();});})`);
 assert.match(await pet.webContents.executeJavaScript(`document.getElementById('bubbleTitle').textContent`),/生气/);
 fs.writeFileSync(path.join(out,'pet-angry.png'),(await pet.webContents.capturePage()).toPNG());
 await pet.webContents.executeJavaScript(`window.workFeiBi.petClick();new Promise(resolve=>window.workFeiBi.onState(s=>{if(!s.timer.reminding)resolve();}))`);
 assert.equal(state().timer.phase,'rest');assert.equal(state().timer.running,true);assert.equal(state().timer.angry,false);
 action('reset');
 await pet.webContents.executeJavaScript(`new Promise(r=>{pose('sway',2000);requestAnimationFrame(()=>r());})`);
 assert.equal(await pet.webContents.executeJavaScript(`stage.classList.contains('sway')`),true);
 await pet.webContents.executeJavaScript(`pose('',0);new Promise(requestAnimationFrame)`);
 fs.writeFileSync(path.join(out,'pet.png'),(await pet.webContents.capturePage()).toPNG());
 fs.writeFileSync(path.join(out,'settings.png'),(await w.webContents.capturePage()).toPNG());
 const media=await pet.webContents.executeJavaScript(`Promise.all(['phoebe_chubby_0.mp3'].map(name=>new Promise((resolve,reject)=>{const a=new Audio('../assets/audio/'+name);a.onloadedmetadata=()=>resolve(a.duration);a.onerror=()=>reject(new Error(name));})))`);
 assert.ok(media.every(n=>n>0));assert.equal(errors.length,0,errors.join('\n'));
 console.log('SMOKE PASS: window setup, original portraits, alpha hit-test, outfit switching, audio decoding, settings IPC, full reminder/ack flow, idle motion, screenshots');
};
